endpoint: https://data.wu.ac.at/sparql/
ui:
    url_prefix_ui: /portalwatch
    port: 2121
rest:
   url_prefix_rest: /portalwatch/api/v1
fetch:
<<<<<<< HEAD
   dir: data
=======
   dir: tests/dumps
>>>>>>> 7ee85ff20fe3b32f90bfb438e68cd32df110a4f1
